Made formatting more readable
gentoo-btw/ramfetch pull request #3
Opened 2022-12-14 19:26 UTC by 21daemones

Used a loop for adding commas instead of sed
Added tabs to align the field
this is my first pull request ;)

2022-12-14 19:46 UTC, WhoseTheNerd requested changes
Pull in PR #1 and then commit it.

2022-12-14 19:46 UTC, WhoseTheNerd commented on ramfetch
> +#!/usr/bin/env bash
Why are you reverting this?

2022-12-14 19:46 UTC, WhoseTheNerd commented on ramfetch
> +        (MemTotal:*)        memtotal="${REPLY//[^0-9]/}" ;;
This as well, did you forget  to update the fork?

2022-12-14 19:46 UTC, WhoseTheNerd commented on ramfetch
> +unit="kB"
I think it is better to write a code to determine the units. So if we have `32187964 kiB` then it should be displayed as 30.69 GiB. Also the units should be switched to kibi/mebi and etc units, we don't need to actually convert it since I'm pretty sure that `/proc/meminfo` already provides that in kibibytes.

2022-12-14 19:46 UTC, WhoseTheNerd commented on ramfetch
> +$greenpart ████      ████      ███      ███ $end  RAM Total: $(echo -e "\t\t") $memtotal $unit
This also means that each of these units must be different.

2022-12-14 19:58 UTC, 21daemones commented on ramfetch
> +        (MemTotal:*)        memtotal="${REPLY//[^0-9]/}" ;;
Yes, I think so... sorry!

2022-12-14 20:21 UTC, 21daemones commented on ramfetch
> +unit="kB"
Good idea! I think we can do that using numfmt.

2022-12-15 04:44 UTC, 21daemones commented
Fixed everything up! Let me know if I should change anything else.

2022-12-15 06:25 UTC, WhoseTheNerd commented
[The output has '\t' characters.](https://i.imgur.com/sZEcnrP.png)

2022-12-15 06:42 UTC, 21daemones commented
Switched from echo to printf; it should work on your machine now.
That also cleared the shellcheck:
`$ shellcheck myscript
No issues detected!`

2022-12-15 10:55 UTC, gentoo-btw commented
> Used a loop for adding commas Added tabs to align the field this is my first pull request ;)

why does the colorblocks not have a gap between "HugePages Total"?.

2022-12-15 14:18 UTC, gentoo-btw commented
> Switched from echo to printf; it should work on your machine now.
> 
> That also cleared the shellcheck:
> 
> `$ shellcheck myscript` `No issues detected!`

reviewdog just doesn't work. but this will be merged anyway.

2022-12-15 14:18 UTC, merged

2022-12-16 16:42 UTC, gentoo-btw commented
> Switched from echo to printf; it should work on your machine now.
> 
> That also cleared the shellcheck:
> 
> `$ shellcheck myscript` `No issues detected!`

@21daemones why is there a gap between hugepages tho.  [this article](https://ostechnix.com/display-memory-information-using-ramfetch-in-linux/) has the ss of it. but it has a gap between hugepages

2022-12-16 16:55 UTC, gentoo-btw commented
> > Switched from echo to printf; it should work on your machine now.
> > That also cleared the shellcheck:
> > `$ shellcheck myscript` `No issues detected!`
> 
> @21daemones why is there a gap between hugepages tho. [this article](https://ostechnix.com/display-memory-information-using-ramfetch-in-linux/) has the ss of it. but it has a gap between hugepages

okay maybe it's just resizing the window makes the problem happen